/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZuriNzilaniFoundationRouteImport } from './routes/zuri-nzilani-foundation'
import { Route as WpTestRouteImport } from './routes/wp-test'
import { Route as ThinkPiecesRouteImport } from './routes/think-pieces'
import { Route as TalkToUsRouteImport } from './routes/talk-to-us'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as RochmanPropertiesRouteImport } from './routes/rochman-properties'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PaediatricAllergyCenterRouteImport } from './routes/paediatric-allergy-center'
import { Route as OurServicesRouteImport } from './routes/our-services'
import { Route as HerenciaRouteImport } from './routes/herencia'
import { Route as FmcgDistributionStudyRouteImport } from './routes/fmcg-distribution-study'
import { Route as FlagshipSolutionsRouteImport } from './routes/flagship-solutions'
import { Route as FeaturedEngagementsArchivesRouteImport } from './routes/featured-engagements-archives'
import { Route as AmeerDevelopersRouteImport } from './routes/ameer-developers'
import { Route as AllianceHospitalRouteImport } from './routes/alliance-hospital'
import { Route as AdvisoryServicesRouteImport } from './routes/advisory-services'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThinkPiecesIndexRouteImport } from './routes/think-pieces.index'
import { Route as FlagshipSolutionsIndexRouteImport } from './routes/flagship-solutions.index'
import { Route as AdvisoryServicesIndexRouteImport } from './routes/advisory-services.index'
import { Route as ThinkPiecesSlugRouteImport } from './routes/think-pieces.$slug'
import { Route as ServicesStrategyRouteImport } from './routes/services/strategy'
import { Route as ServicesSalesRouteImport } from './routes/services/sales'
import { Route as ServicesResearchRouteImport } from './routes/services/research'
import { Route as ServicesMarketingRouteImport } from './routes/services/marketing'
import { Route as ServicesCommunicationRouteImport } from './routes/services/communication'
import { Route as FlagshipSolutionsSmeGrowthBlueprintRouteImport } from './routes/flagship-solutions.sme-growth-blueprint'
import { Route as FlagshipSolutionsRevenueAccelerationRouteImport } from './routes/flagship-solutions.revenue-acceleration'
import { Route as FlagshipSolutionsProgrammeDesignRouteImport } from './routes/flagship-solutions.programme-design'
import { Route as FlagshipSolutionsFeasibilityMarketEntryRouteImport } from './routes/flagship-solutions.feasibility-market-entry'
import { Route as FlagshipSolutionsCapitalReadinessRouteImport } from './routes/flagship-solutions.capital-readiness'
import { Route as AdvisoryServicesExecutiveAdvisoryRouteImport } from './routes/advisory-services.executive-advisory'
import { Route as AdvisoryServicesConsultingClinicRouteImport } from './routes/advisory-services.consulting-clinic'
import { Route as AdvisoryServicesBusinessDiagnosticRouteImport } from './routes/advisory-services.business-diagnostic'

const ZuriNzilaniFoundationRoute = ZuriNzilaniFoundationRouteImport.update({
  id: '/zuri-nzilani-foundation',
  path: '/zuri-nzilani-foundation',
  getParentRoute: () => rootRouteImport,
} as any)
const WpTestRoute = WpTestRouteImport.update({
  id: '/wp-test',
  path: '/wp-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ThinkPiecesRoute = ThinkPiecesRouteImport.update({
  id: '/think-pieces',
  path: '/think-pieces',
  getParentRoute: () => rootRouteImport,
} as any)
const TalkToUsRoute = TalkToUsRouteImport.update({
  id: '/talk-to-us',
  path: '/talk-to-us',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const RochmanPropertiesRoute = RochmanPropertiesRouteImport.update({
  id: '/rochman-properties',
  path: '/rochman-properties',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PaediatricAllergyCenterRoute = PaediatricAllergyCenterRouteImport.update({
  id: '/paediatric-allergy-center',
  path: '/paediatric-allergy-center',
  getParentRoute: () => rootRouteImport,
} as any)
const OurServicesRoute = OurServicesRouteImport.update({
  id: '/our-services',
  path: '/our-services',
  getParentRoute: () => rootRouteImport,
} as any)
const HerenciaRoute = HerenciaRouteImport.update({
  id: '/herencia',
  path: '/herencia',
  getParentRoute: () => rootRouteImport,
} as any)
const FmcgDistributionStudyRoute = FmcgDistributionStudyRouteImport.update({
  id: '/fmcg-distribution-study',
  path: '/fmcg-distribution-study',
  getParentRoute: () => rootRouteImport,
} as any)
const FlagshipSolutionsRoute = FlagshipSolutionsRouteImport.update({
  id: '/flagship-solutions',
  path: '/flagship-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturedEngagementsArchivesRoute =
  FeaturedEngagementsArchivesRouteImport.update({
    id: '/featured-engagements-archives',
    path: '/featured-engagements-archives',
    getParentRoute: () => rootRouteImport,
  } as any)
const AmeerDevelopersRoute = AmeerDevelopersRouteImport.update({
  id: '/ameer-developers',
  path: '/ameer-developers',
  getParentRoute: () => rootRouteImport,
} as any)
const AllianceHospitalRoute = AllianceHospitalRouteImport.update({
  id: '/alliance-hospital',
  path: '/alliance-hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisoryServicesRoute = AdvisoryServicesRouteImport.update({
  id: '/advisory-services',
  path: '/advisory-services',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThinkPiecesIndexRoute = ThinkPiecesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ThinkPiecesRoute,
} as any)
const FlagshipSolutionsIndexRoute = FlagshipSolutionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FlagshipSolutionsRoute,
} as any)
const AdvisoryServicesIndexRoute = AdvisoryServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdvisoryServicesRoute,
} as any)
const ThinkPiecesSlugRoute = ThinkPiecesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ThinkPiecesRoute,
} as any)
const ServicesStrategyRoute = ServicesStrategyRouteImport.update({
  id: '/services/strategy',
  path: '/services/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSalesRoute = ServicesSalesRouteImport.update({
  id: '/services/sales',
  path: '/services/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesResearchRoute = ServicesResearchRouteImport.update({
  id: '/services/research',
  path: '/services/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMarketingRoute = ServicesMarketingRouteImport.update({
  id: '/services/marketing',
  path: '/services/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCommunicationRoute = ServicesCommunicationRouteImport.update({
  id: '/services/communication',
  path: '/services/communication',
  getParentRoute: () => rootRouteImport,
} as any)
const FlagshipSolutionsSmeGrowthBlueprintRoute =
  FlagshipSolutionsSmeGrowthBlueprintRouteImport.update({
    id: '/sme-growth-blueprint',
    path: '/sme-growth-blueprint',
    getParentRoute: () => FlagshipSolutionsRoute,
  } as any)
const FlagshipSolutionsRevenueAccelerationRoute =
  FlagshipSolutionsRevenueAccelerationRouteImport.update({
    id: '/revenue-acceleration',
    path: '/revenue-acceleration',
    getParentRoute: () => FlagshipSolutionsRoute,
  } as any)
const FlagshipSolutionsProgrammeDesignRoute =
  FlagshipSolutionsProgrammeDesignRouteImport.update({
    id: '/programme-design',
    path: '/programme-design',
    getParentRoute: () => FlagshipSolutionsRoute,
  } as any)
const FlagshipSolutionsFeasibilityMarketEntryRoute =
  FlagshipSolutionsFeasibilityMarketEntryRouteImport.update({
    id: '/feasibility-market-entry',
    path: '/feasibility-market-entry',
    getParentRoute: () => FlagshipSolutionsRoute,
  } as any)
const FlagshipSolutionsCapitalReadinessRoute =
  FlagshipSolutionsCapitalReadinessRouteImport.update({
    id: '/capital-readiness',
    path: '/capital-readiness',
    getParentRoute: () => FlagshipSolutionsRoute,
  } as any)
const AdvisoryServicesExecutiveAdvisoryRoute =
  AdvisoryServicesExecutiveAdvisoryRouteImport.update({
    id: '/executive-advisory',
    path: '/executive-advisory',
    getParentRoute: () => AdvisoryServicesRoute,
  } as any)
const AdvisoryServicesConsultingClinicRoute =
  AdvisoryServicesConsultingClinicRouteImport.update({
    id: '/consulting-clinic',
    path: '/consulting-clinic',
    getParentRoute: () => AdvisoryServicesRoute,
  } as any)
const AdvisoryServicesBusinessDiagnosticRoute =
  AdvisoryServicesBusinessDiagnosticRouteImport.update({
    id: '/business-diagnostic',
    path: '/business-diagnostic',
    getParentRoute: () => AdvisoryServicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory-services': typeof AdvisoryServicesRouteWithChildren
  '/alliance-hospital': typeof AllianceHospitalRoute
  '/ameer-developers': typeof AmeerDevelopersRoute
  '/featured-engagements-archives': typeof FeaturedEngagementsArchivesRoute
  '/flagship-solutions': typeof FlagshipSolutionsRouteWithChildren
  '/fmcg-distribution-study': typeof FmcgDistributionStudyRoute
  '/herencia': typeof HerenciaRoute
  '/our-services': typeof OurServicesRoute
  '/paediatric-allergy-center': typeof PaediatricAllergyCenterRoute
  '/portfolio': typeof PortfolioRoute
  '/rochman-properties': typeof RochmanPropertiesRoute
  '/solutions': typeof SolutionsRoute
  '/talk-to-us': typeof TalkToUsRoute
  '/think-pieces': typeof ThinkPiecesRouteWithChildren
  '/wp-test': typeof WpTestRoute
  '/zuri-nzilani-foundation': typeof ZuriNzilaniFoundationRoute
  '/advisory-services/business-diagnostic': typeof AdvisoryServicesBusinessDiagnosticRoute
  '/advisory-services/consulting-clinic': typeof AdvisoryServicesConsultingClinicRoute
  '/advisory-services/executive-advisory': typeof AdvisoryServicesExecutiveAdvisoryRoute
  '/flagship-solutions/capital-readiness': typeof FlagshipSolutionsCapitalReadinessRoute
  '/flagship-solutions/feasibility-market-entry': typeof FlagshipSolutionsFeasibilityMarketEntryRoute
  '/flagship-solutions/programme-design': typeof FlagshipSolutionsProgrammeDesignRoute
  '/flagship-solutions/revenue-acceleration': typeof FlagshipSolutionsRevenueAccelerationRoute
  '/flagship-solutions/sme-growth-blueprint': typeof FlagshipSolutionsSmeGrowthBlueprintRoute
  '/services/communication': typeof ServicesCommunicationRoute
  '/services/marketing': typeof ServicesMarketingRoute
  '/services/research': typeof ServicesResearchRoute
  '/services/sales': typeof ServicesSalesRoute
  '/services/strategy': typeof ServicesStrategyRoute
  '/think-pieces/$slug': typeof ThinkPiecesSlugRoute
  '/advisory-services/': typeof AdvisoryServicesIndexRoute
  '/flagship-solutions/': typeof FlagshipSolutionsIndexRoute
  '/think-pieces/': typeof ThinkPiecesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alliance-hospital': typeof AllianceHospitalRoute
  '/ameer-developers': typeof AmeerDevelopersRoute
  '/featured-engagements-archives': typeof FeaturedEngagementsArchivesRoute
  '/fmcg-distribution-study': typeof FmcgDistributionStudyRoute
  '/herencia': typeof HerenciaRoute
  '/our-services': typeof OurServicesRoute
  '/paediatric-allergy-center': typeof PaediatricAllergyCenterRoute
  '/portfolio': typeof PortfolioRoute
  '/rochman-properties': typeof RochmanPropertiesRoute
  '/solutions': typeof SolutionsRoute
  '/talk-to-us': typeof TalkToUsRoute
  '/wp-test': typeof WpTestRoute
  '/zuri-nzilani-foundation': typeof ZuriNzilaniFoundationRoute
  '/advisory-services/business-diagnostic': typeof AdvisoryServicesBusinessDiagnosticRoute
  '/advisory-services/consulting-clinic': typeof AdvisoryServicesConsultingClinicRoute
  '/advisory-services/executive-advisory': typeof AdvisoryServicesExecutiveAdvisoryRoute
  '/flagship-solutions/capital-readiness': typeof FlagshipSolutionsCapitalReadinessRoute
  '/flagship-solutions/feasibility-market-entry': typeof FlagshipSolutionsFeasibilityMarketEntryRoute
  '/flagship-solutions/programme-design': typeof FlagshipSolutionsProgrammeDesignRoute
  '/flagship-solutions/revenue-acceleration': typeof FlagshipSolutionsRevenueAccelerationRoute
  '/flagship-solutions/sme-growth-blueprint': typeof FlagshipSolutionsSmeGrowthBlueprintRoute
  '/services/communication': typeof ServicesCommunicationRoute
  '/services/marketing': typeof ServicesMarketingRoute
  '/services/research': typeof ServicesResearchRoute
  '/services/sales': typeof ServicesSalesRoute
  '/services/strategy': typeof ServicesStrategyRoute
  '/think-pieces/$slug': typeof ThinkPiecesSlugRoute
  '/advisory-services': typeof AdvisoryServicesIndexRoute
  '/flagship-solutions': typeof FlagshipSolutionsIndexRoute
  '/think-pieces': typeof ThinkPiecesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory-services': typeof AdvisoryServicesRouteWithChildren
  '/alliance-hospital': typeof AllianceHospitalRoute
  '/ameer-developers': typeof AmeerDevelopersRoute
  '/featured-engagements-archives': typeof FeaturedEngagementsArchivesRoute
  '/flagship-solutions': typeof FlagshipSolutionsRouteWithChildren
  '/fmcg-distribution-study': typeof FmcgDistributionStudyRoute
  '/herencia': typeof HerenciaRoute
  '/our-services': typeof OurServicesRoute
  '/paediatric-allergy-center': typeof PaediatricAllergyCenterRoute
  '/portfolio': typeof PortfolioRoute
  '/rochman-properties': typeof RochmanPropertiesRoute
  '/solutions': typeof SolutionsRoute
  '/talk-to-us': typeof TalkToUsRoute
  '/think-pieces': typeof ThinkPiecesRouteWithChildren
  '/wp-test': typeof WpTestRoute
  '/zuri-nzilani-foundation': typeof ZuriNzilaniFoundationRoute
  '/advisory-services/business-diagnostic': typeof AdvisoryServicesBusinessDiagnosticRoute
  '/advisory-services/consulting-clinic': typeof AdvisoryServicesConsultingClinicRoute
  '/advisory-services/executive-advisory': typeof AdvisoryServicesExecutiveAdvisoryRoute
  '/flagship-solutions/capital-readiness': typeof FlagshipSolutionsCapitalReadinessRoute
  '/flagship-solutions/feasibility-market-entry': typeof FlagshipSolutionsFeasibilityMarketEntryRoute
  '/flagship-solutions/programme-design': typeof FlagshipSolutionsProgrammeDesignRoute
  '/flagship-solutions/revenue-acceleration': typeof FlagshipSolutionsRevenueAccelerationRoute
  '/flagship-solutions/sme-growth-blueprint': typeof FlagshipSolutionsSmeGrowthBlueprintRoute
  '/services/communication': typeof ServicesCommunicationRoute
  '/services/marketing': typeof ServicesMarketingRoute
  '/services/research': typeof ServicesResearchRoute
  '/services/sales': typeof ServicesSalesRoute
  '/services/strategy': typeof ServicesStrategyRoute
  '/think-pieces/$slug': typeof ThinkPiecesSlugRoute
  '/advisory-services/': typeof AdvisoryServicesIndexRoute
  '/flagship-solutions/': typeof FlagshipSolutionsIndexRoute
  '/think-pieces/': typeof ThinkPiecesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advisory-services'
    | '/alliance-hospital'
    | '/ameer-developers'
    | '/featured-engagements-archives'
    | '/flagship-solutions'
    | '/fmcg-distribution-study'
    | '/herencia'
    | '/our-services'
    | '/paediatric-allergy-center'
    | '/portfolio'
    | '/rochman-properties'
    | '/solutions'
    | '/talk-to-us'
    | '/think-pieces'
    | '/wp-test'
    | '/zuri-nzilani-foundation'
    | '/advisory-services/business-diagnostic'
    | '/advisory-services/consulting-clinic'
    | '/advisory-services/executive-advisory'
    | '/flagship-solutions/capital-readiness'
    | '/flagship-solutions/feasibility-market-entry'
    | '/flagship-solutions/programme-design'
    | '/flagship-solutions/revenue-acceleration'
    | '/flagship-solutions/sme-growth-blueprint'
    | '/services/communication'
    | '/services/marketing'
    | '/services/research'
    | '/services/sales'
    | '/services/strategy'
    | '/think-pieces/$slug'
    | '/advisory-services/'
    | '/flagship-solutions/'
    | '/think-pieces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/alliance-hospital'
    | '/ameer-developers'
    | '/featured-engagements-archives'
    | '/fmcg-distribution-study'
    | '/herencia'
    | '/our-services'
    | '/paediatric-allergy-center'
    | '/portfolio'
    | '/rochman-properties'
    | '/solutions'
    | '/talk-to-us'
    | '/wp-test'
    | '/zuri-nzilani-foundation'
    | '/advisory-services/business-diagnostic'
    | '/advisory-services/consulting-clinic'
    | '/advisory-services/executive-advisory'
    | '/flagship-solutions/capital-readiness'
    | '/flagship-solutions/feasibility-market-entry'
    | '/flagship-solutions/programme-design'
    | '/flagship-solutions/revenue-acceleration'
    | '/flagship-solutions/sme-growth-blueprint'
    | '/services/communication'
    | '/services/marketing'
    | '/services/research'
    | '/services/sales'
    | '/services/strategy'
    | '/think-pieces/$slug'
    | '/advisory-services'
    | '/flagship-solutions'
    | '/think-pieces'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advisory-services'
    | '/alliance-hospital'
    | '/ameer-developers'
    | '/featured-engagements-archives'
    | '/flagship-solutions'
    | '/fmcg-distribution-study'
    | '/herencia'
    | '/our-services'
    | '/paediatric-allergy-center'
    | '/portfolio'
    | '/rochman-properties'
    | '/solutions'
    | '/talk-to-us'
    | '/think-pieces'
    | '/wp-test'
    | '/zuri-nzilani-foundation'
    | '/advisory-services/business-diagnostic'
    | '/advisory-services/consulting-clinic'
    | '/advisory-services/executive-advisory'
    | '/flagship-solutions/capital-readiness'
    | '/flagship-solutions/feasibility-market-entry'
    | '/flagship-solutions/programme-design'
    | '/flagship-solutions/revenue-acceleration'
    | '/flagship-solutions/sme-growth-blueprint'
    | '/services/communication'
    | '/services/marketing'
    | '/services/research'
    | '/services/sales'
    | '/services/strategy'
    | '/think-pieces/$slug'
    | '/advisory-services/'
    | '/flagship-solutions/'
    | '/think-pieces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvisoryServicesRoute: typeof AdvisoryServicesRouteWithChildren
  AllianceHospitalRoute: typeof AllianceHospitalRoute
  AmeerDevelopersRoute: typeof AmeerDevelopersRoute
  FeaturedEngagementsArchivesRoute: typeof FeaturedEngagementsArchivesRoute
  FlagshipSolutionsRoute: typeof FlagshipSolutionsRouteWithChildren
  FmcgDistributionStudyRoute: typeof FmcgDistributionStudyRoute
  HerenciaRoute: typeof HerenciaRoute
  OurServicesRoute: typeof OurServicesRoute
  PaediatricAllergyCenterRoute: typeof PaediatricAllergyCenterRoute
  PortfolioRoute: typeof PortfolioRoute
  RochmanPropertiesRoute: typeof RochmanPropertiesRoute
  SolutionsRoute: typeof SolutionsRoute
  TalkToUsRoute: typeof TalkToUsRoute
  ThinkPiecesRoute: typeof ThinkPiecesRouteWithChildren
  WpTestRoute: typeof WpTestRoute
  ZuriNzilaniFoundationRoute: typeof ZuriNzilaniFoundationRoute
  ServicesCommunicationRoute: typeof ServicesCommunicationRoute
  ServicesMarketingRoute: typeof ServicesMarketingRoute
  ServicesResearchRoute: typeof ServicesResearchRoute
  ServicesSalesRoute: typeof ServicesSalesRoute
  ServicesStrategyRoute: typeof ServicesStrategyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zuri-nzilani-foundation': {
      id: '/zuri-nzilani-foundation'
      path: '/zuri-nzilani-foundation'
      fullPath: '/zuri-nzilani-foundation'
      preLoaderRoute: typeof ZuriNzilaniFoundationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wp-test': {
      id: '/wp-test'
      path: '/wp-test'
      fullPath: '/wp-test'
      preLoaderRoute: typeof WpTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/think-pieces': {
      id: '/think-pieces'
      path: '/think-pieces'
      fullPath: '/think-pieces'
      preLoaderRoute: typeof ThinkPiecesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talk-to-us': {
      id: '/talk-to-us'
      path: '/talk-to-us'
      fullPath: '/talk-to-us'
      preLoaderRoute: typeof TalkToUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rochman-properties': {
      id: '/rochman-properties'
      path: '/rochman-properties'
      fullPath: '/rochman-properties'
      preLoaderRoute: typeof RochmanPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paediatric-allergy-center': {
      id: '/paediatric-allergy-center'
      path: '/paediatric-allergy-center'
      fullPath: '/paediatric-allergy-center'
      preLoaderRoute: typeof PaediatricAllergyCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-services': {
      id: '/our-services'
      path: '/our-services'
      fullPath: '/our-services'
      preLoaderRoute: typeof OurServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/herencia': {
      id: '/herencia'
      path: '/herencia'
      fullPath: '/herencia'
      preLoaderRoute: typeof HerenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fmcg-distribution-study': {
      id: '/fmcg-distribution-study'
      path: '/fmcg-distribution-study'
      fullPath: '/fmcg-distribution-study'
      preLoaderRoute: typeof FmcgDistributionStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flagship-solutions': {
      id: '/flagship-solutions'
      path: '/flagship-solutions'
      fullPath: '/flagship-solutions'
      preLoaderRoute: typeof FlagshipSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/featured-engagements-archives': {
      id: '/featured-engagements-archives'
      path: '/featured-engagements-archives'
      fullPath: '/featured-engagements-archives'
      preLoaderRoute: typeof FeaturedEngagementsArchivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ameer-developers': {
      id: '/ameer-developers'
      path: '/ameer-developers'
      fullPath: '/ameer-developers'
      preLoaderRoute: typeof AmeerDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alliance-hospital': {
      id: '/alliance-hospital'
      path: '/alliance-hospital'
      fullPath: '/alliance-hospital'
      preLoaderRoute: typeof AllianceHospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisory-services': {
      id: '/advisory-services'
      path: '/advisory-services'
      fullPath: '/advisory-services'
      preLoaderRoute: typeof AdvisoryServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/think-pieces/': {
      id: '/think-pieces/'
      path: '/'
      fullPath: '/think-pieces/'
      preLoaderRoute: typeof ThinkPiecesIndexRouteImport
      parentRoute: typeof ThinkPiecesRoute
    }
    '/flagship-solutions/': {
      id: '/flagship-solutions/'
      path: '/'
      fullPath: '/flagship-solutions/'
      preLoaderRoute: typeof FlagshipSolutionsIndexRouteImport
      parentRoute: typeof FlagshipSolutionsRoute
    }
    '/advisory-services/': {
      id: '/advisory-services/'
      path: '/'
      fullPath: '/advisory-services/'
      preLoaderRoute: typeof AdvisoryServicesIndexRouteImport
      parentRoute: typeof AdvisoryServicesRoute
    }
    '/think-pieces/$slug': {
      id: '/think-pieces/$slug'
      path: '/$slug'
      fullPath: '/think-pieces/$slug'
      preLoaderRoute: typeof ThinkPiecesSlugRouteImport
      parentRoute: typeof ThinkPiecesRoute
    }
    '/services/strategy': {
      id: '/services/strategy'
      path: '/services/strategy'
      fullPath: '/services/strategy'
      preLoaderRoute: typeof ServicesStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/sales': {
      id: '/services/sales'
      path: '/services/sales'
      fullPath: '/services/sales'
      preLoaderRoute: typeof ServicesSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/research': {
      id: '/services/research'
      path: '/services/research'
      fullPath: '/services/research'
      preLoaderRoute: typeof ServicesResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/marketing': {
      id: '/services/marketing'
      path: '/services/marketing'
      fullPath: '/services/marketing'
      preLoaderRoute: typeof ServicesMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/communication': {
      id: '/services/communication'
      path: '/services/communication'
      fullPath: '/services/communication'
      preLoaderRoute: typeof ServicesCommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flagship-solutions/sme-growth-blueprint': {
      id: '/flagship-solutions/sme-growth-blueprint'
      path: '/sme-growth-blueprint'
      fullPath: '/flagship-solutions/sme-growth-blueprint'
      preLoaderRoute: typeof FlagshipSolutionsSmeGrowthBlueprintRouteImport
      parentRoute: typeof FlagshipSolutionsRoute
    }
    '/flagship-solutions/revenue-acceleration': {
      id: '/flagship-solutions/revenue-acceleration'
      path: '/revenue-acceleration'
      fullPath: '/flagship-solutions/revenue-acceleration'
      preLoaderRoute: typeof FlagshipSolutionsRevenueAccelerationRouteImport
      parentRoute: typeof FlagshipSolutionsRoute
    }
    '/flagship-solutions/programme-design': {
      id: '/flagship-solutions/programme-design'
      path: '/programme-design'
      fullPath: '/flagship-solutions/programme-design'
      preLoaderRoute: typeof FlagshipSolutionsProgrammeDesignRouteImport
      parentRoute: typeof FlagshipSolutionsRoute
    }
    '/flagship-solutions/feasibility-market-entry': {
      id: '/flagship-solutions/feasibility-market-entry'
      path: '/feasibility-market-entry'
      fullPath: '/flagship-solutions/feasibility-market-entry'
      preLoaderRoute: typeof FlagshipSolutionsFeasibilityMarketEntryRouteImport
      parentRoute: typeof FlagshipSolutionsRoute
    }
    '/flagship-solutions/capital-readiness': {
      id: '/flagship-solutions/capital-readiness'
      path: '/capital-readiness'
      fullPath: '/flagship-solutions/capital-readiness'
      preLoaderRoute: typeof FlagshipSolutionsCapitalReadinessRouteImport
      parentRoute: typeof FlagshipSolutionsRoute
    }
    '/advisory-services/executive-advisory': {
      id: '/advisory-services/executive-advisory'
      path: '/executive-advisory'
      fullPath: '/advisory-services/executive-advisory'
      preLoaderRoute: typeof AdvisoryServicesExecutiveAdvisoryRouteImport
      parentRoute: typeof AdvisoryServicesRoute
    }
    '/advisory-services/consulting-clinic': {
      id: '/advisory-services/consulting-clinic'
      path: '/consulting-clinic'
      fullPath: '/advisory-services/consulting-clinic'
      preLoaderRoute: typeof AdvisoryServicesConsultingClinicRouteImport
      parentRoute: typeof AdvisoryServicesRoute
    }
    '/advisory-services/business-diagnostic': {
      id: '/advisory-services/business-diagnostic'
      path: '/business-diagnostic'
      fullPath: '/advisory-services/business-diagnostic'
      preLoaderRoute: typeof AdvisoryServicesBusinessDiagnosticRouteImport
      parentRoute: typeof AdvisoryServicesRoute
    }
  }
}

interface AdvisoryServicesRouteChildren {
  AdvisoryServicesBusinessDiagnosticRoute: typeof AdvisoryServicesBusinessDiagnosticRoute
  AdvisoryServicesConsultingClinicRoute: typeof AdvisoryServicesConsultingClinicRoute
  AdvisoryServicesExecutiveAdvisoryRoute: typeof AdvisoryServicesExecutiveAdvisoryRoute
  AdvisoryServicesIndexRoute: typeof AdvisoryServicesIndexRoute
}

const AdvisoryServicesRouteChildren: AdvisoryServicesRouteChildren = {
  AdvisoryServicesBusinessDiagnosticRoute:
    AdvisoryServicesBusinessDiagnosticRoute,
  AdvisoryServicesConsultingClinicRoute: AdvisoryServicesConsultingClinicRoute,
  AdvisoryServicesExecutiveAdvisoryRoute:
    AdvisoryServicesExecutiveAdvisoryRoute,
  AdvisoryServicesIndexRoute: AdvisoryServicesIndexRoute,
}

const AdvisoryServicesRouteWithChildren =
  AdvisoryServicesRoute._addFileChildren(AdvisoryServicesRouteChildren)

interface FlagshipSolutionsRouteChildren {
  FlagshipSolutionsCapitalReadinessRoute: typeof FlagshipSolutionsCapitalReadinessRoute
  FlagshipSolutionsFeasibilityMarketEntryRoute: typeof FlagshipSolutionsFeasibilityMarketEntryRoute
  FlagshipSolutionsProgrammeDesignRoute: typeof FlagshipSolutionsProgrammeDesignRoute
  FlagshipSolutionsRevenueAccelerationRoute: typeof FlagshipSolutionsRevenueAccelerationRoute
  FlagshipSolutionsSmeGrowthBlueprintRoute: typeof FlagshipSolutionsSmeGrowthBlueprintRoute
  FlagshipSolutionsIndexRoute: typeof FlagshipSolutionsIndexRoute
}

const FlagshipSolutionsRouteChildren: FlagshipSolutionsRouteChildren = {
  FlagshipSolutionsCapitalReadinessRoute:
    FlagshipSolutionsCapitalReadinessRoute,
  FlagshipSolutionsFeasibilityMarketEntryRoute:
    FlagshipSolutionsFeasibilityMarketEntryRoute,
  FlagshipSolutionsProgrammeDesignRoute: FlagshipSolutionsProgrammeDesignRoute,
  FlagshipSolutionsRevenueAccelerationRoute:
    FlagshipSolutionsRevenueAccelerationRoute,
  FlagshipSolutionsSmeGrowthBlueprintRoute:
    FlagshipSolutionsSmeGrowthBlueprintRoute,
  FlagshipSolutionsIndexRoute: FlagshipSolutionsIndexRoute,
}

const FlagshipSolutionsRouteWithChildren =
  FlagshipSolutionsRoute._addFileChildren(FlagshipSolutionsRouteChildren)

interface ThinkPiecesRouteChildren {
  ThinkPiecesSlugRoute: typeof ThinkPiecesSlugRoute
  ThinkPiecesIndexRoute: typeof ThinkPiecesIndexRoute
}

const ThinkPiecesRouteChildren: ThinkPiecesRouteChildren = {
  ThinkPiecesSlugRoute: ThinkPiecesSlugRoute,
  ThinkPiecesIndexRoute: ThinkPiecesIndexRoute,
}

const ThinkPiecesRouteWithChildren = ThinkPiecesRoute._addFileChildren(
  ThinkPiecesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvisoryServicesRoute: AdvisoryServicesRouteWithChildren,
  AllianceHospitalRoute: AllianceHospitalRoute,
  AmeerDevelopersRoute: AmeerDevelopersRoute,
  FeaturedEngagementsArchivesRoute: FeaturedEngagementsArchivesRoute,
  FlagshipSolutionsRoute: FlagshipSolutionsRouteWithChildren,
  FmcgDistributionStudyRoute: FmcgDistributionStudyRoute,
  HerenciaRoute: HerenciaRoute,
  OurServicesRoute: OurServicesRoute,
  PaediatricAllergyCenterRoute: PaediatricAllergyCenterRoute,
  PortfolioRoute: PortfolioRoute,
  RochmanPropertiesRoute: RochmanPropertiesRoute,
  SolutionsRoute: SolutionsRoute,
  TalkToUsRoute: TalkToUsRoute,
  ThinkPiecesRoute: ThinkPiecesRouteWithChildren,
  WpTestRoute: WpTestRoute,
  ZuriNzilaniFoundationRoute: ZuriNzilaniFoundationRoute,
  ServicesCommunicationRoute: ServicesCommunicationRoute,
  ServicesMarketingRoute: ServicesMarketingRoute,
  ServicesResearchRoute: ServicesResearchRoute,
  ServicesSalesRoute: ServicesSalesRoute,
  ServicesStrategyRoute: ServicesStrategyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
